# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('database', '0009_merge_20171109_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('authtoken.token',),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(upload_to=b''),
        ),
    ]
