# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20171128_1117'),
        ('database', '0010_auto_20171117_0044'),
    ]

    operations = [
    ]
