# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_user_is_verified'),
        ('database', '0029_merge_20171201_0952'),
    ]

    operations = [
    ]
