# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20171110_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='letter',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='capsule',
            name='media',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
