# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 20:21
from __future__ import unicode_literals

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20171110_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='letter',
            field=models.FileField(blank=True, upload_to=database.models._upload_path),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='media',
            field=models.FileField(blank=True, upload_to=database.models._upload_path),
        ),
    ]
