# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 20:31
from __future__ import unicode_literals

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20171113_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to=database.models._upload_path),
        ),
    ]
