# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_merge_20171109_2338'),
        ('database', '0012_auto_20171113_2031'),
    ]

    operations = [
    ]
