# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20171127_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsule',
            name='letter',
        ),
        migrations.AddField(
            model_name='capsule',
            name='letter',
            field=models.ManyToManyField(blank=True, related_name='letters', to='database.Letters'),
        ),
        migrations.RemoveField(
            model_name='capsule',
            name='media',
        ),
        migrations.AddField(
            model_name='capsule',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='media', to='database.Media'),
        ),
    ]
