# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_capsule_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='location',
            new_name='file',
        ),
    ]
