# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 04:04
from __future__ import unicode_literals

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_merge_20171128_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to=database.models._upload_path),
        ),
    ]
