# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20171128_2004'),
        ('database', '0024_auto_20171128_1853'),
    ]

    operations = [
    ]
