# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_merge_20171129_0944'),
        ('database', '0026_auto_20171129_1219'),
    ]

    operations = [
    ]
