# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_merge_20171130_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('text', models.TextField(default='')),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_capsule', to='database.Capsule')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Letters',
            new_name='Letter',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='owner',
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='cid',
            new_name='capsule',
        ),
        migrations.RemoveField(
            model_name='media',
            name='cid',
        ),
        migrations.AddField(
            model_name='media',
            name='capsule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_capsule', to='database.Capsule'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
