# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_merge_20171130_1507'),
        ('database', '0027_merge_20171130_1459'),
    ]

    operations = [
    ]
