# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_auto_20171201_0925'),
        ('database', '0028_merge_20171201_0915'),
    ]

    operations = [
    ]
