# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_merge_20171204_1725'),
        ('database', '0030_auto_20171203_1325'),
    ]

    operations = [
    ]
